spring:
  application:
    env: DEV
    name: inmueble-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_inmueble
    username: postgres
    password: F2developer97
    driver-class-name: org.postgresql.Driver
    #validationQuery: SELECT 1
  jpa:
    show-sql: true
    #database: postgressSql
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQLDialect
     ddl-auto: update

eureka:
  instance:
    preferIpAddress: true
    ipAddress: 172.17.32.1
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#ribbon:
  #eureka:
    #enabled: true

server:
  port: 3333

service:
  security:
    secure-key-username: usernameSecurity
    secure-key-password: passwordSecurity!
    secure-key-username-2: usernameSecurity2
    secure-key-password-2: passwordSecurity2!
