server:
  port: 8081

spring:
  application:
    name: micro-apigateway
  datasource:
    url: jdbc:mysql://localhost:3306/db_gateway?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: F2developer97
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inmueble-service
          uri: http://localhost:3333
          predicates:
            - Path=/api/inmueble/**
          filters:
            - name: CustomFilterBasic
              args:
                name: usernameSecurity
                password: passwordSecurity!
        - id: compra-service
          uri: http://localhost:4444
          predicates:
            - Path=/api/compra/**
          filters:
            - name: CustomFilterBasic
              args:
                name: userSecCompra
                password: example-password

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: RandomSecretKey123456789!RandomSecretKey123456789!RandomSecretKey123456789!
    expiration-in-ms: 900000


logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.security.web: TRACE
  org.springframework.security.web.server: TRACE
  org.springframework.security.web.server.authentication: TRACE